source(output(
		city as string,
		customer_id as string,
		customer_segment as string,
		date_of_birth as date,
		email as string,
		first_name as string,
		last_name as string,
		registration_date as date,
		state as string
	),
	allowSchemaDrift: true,
	validateSchema: false,
	ignoreNoFilesFound: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'silver/customers') ~> customers
source(output(
		account_id as string,
		customer_id as string,
		account_type as string,
		account_open_date as date,
		account_status as string,
		balance as decimal(10,0),
		branch_id as string
	),
	allowSchemaDrift: true,
	validateSchema: false,
	ignoreNoFilesFound: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'silver/accounts') ~> accounts
source(output(
		branch_id as string,
		branch_name as string,
		city as string,
		state as string,
		region as string
	),
	allowSchemaDrift: true,
	validateSchema: false,
	ignoreNoFilesFound: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'silver/branches') ~> branches
source(output(
		transaction_id as string,
		account_id as string,
		transaction_date as date,
		transaction_type as string,
		amount as decimal(10,0),
		payment_method as string,
		merchant as string,
		transaction_status as string
	),
	allowSchemaDrift: true,
	validateSchema: false,
	ignoreNoFilesFound: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'silver/transactions') ~> transactions
transactions, accounts join(transactions@account_id == accounts@account_id,
	joinType:'inner',
	matchType:'exact',
	ignoreSpaces: false,
	broadcast: 'auto')~> join1
join1, customers join(accounts@customer_id == customers@customer_id,
	joinType:'inner',
	matchType:'exact',
	ignoreSpaces: false,
	broadcast: 'auto')~> join2
join2, branches join(accounts@branch_id == branches@branch_id,
	joinType:'inner',
	matchType:'exact',
	ignoreSpaces: false,
	broadcast: 'auto')~> join3
join3 aggregate(groupBy(customers@customer_id),
	transaction_count = count(transaction_id),
		total_transaction_amount = sum(amount),
		average_transaction_amount = avg(amount),
		unique_transaction_types = countDistinct(transaction_type)) ~> aggregateTransactions
customers sink(allowSchemaDrift: true,
	validateSchema: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'gold/customers',
	overwrite: true,
	mergeSchema: false,
	autoCompact: false,
	optimizedWrite: false,
	vacuum: 0,
	deletable: false,
	insertable: true,
	updateable: false,
	upsertable: false,
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> custdim
accounts sink(allowSchemaDrift: true,
	validateSchema: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'gold/accounts',
	overwrite: true,
	mergeSchema: false,
	autoCompact: false,
	optimizedWrite: false,
	vacuum: 0,
	deletable: false,
	insertable: true,
	updateable: false,
	upsertable: false,
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> sinkdimaccount
branches sink(allowSchemaDrift: true,
	validateSchema: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'gold/branches',
	overwrite: true,
	mergeSchema: false,
	autoCompact: false,
	optimizedWrite: false,
	vacuum: 0,
	deletable: false,
	insertable: true,
	updateable: false,
	upsertable: false,
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> sinkdimBranches
aggregateTransactions sink(allowSchemaDrift: true,
	validateSchema: false,
	format: 'delta',
	fileSystem: 'banking',
	folderPath: 'gold/transactions',
	overwrite: true,
	mergeSchema: false,
	autoCompact: false,
	optimizedWrite: false,
	vacuum: 0,
	deletable: false,
	insertable: true,
	updateable: false,
	upsertable: false,
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> customertransactionsummary